//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IQChartConnString {
            get {
                return ((string)(this["IQChartConnString"]));
            }
            set {
                this["IQChartConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>dtl_CD4</string>
  <string>dtl_sti</string>
  <string>dtl_height</string>
  <string>dtl_weight</string>
  <string>dtl_oi</string>
  <string>dtl_regimen</string>
  <string>dtl_who</string>
  <string>dtl_TBScreen</string>
  <string>dtl_TBTreat</string>
  <string>dtl_pregnancy</string>
  <string>dtl_phyadh</string>
  <string>dtl_meds</string>
  <string>dtl_hosp</string>
  <string>mst_ptn</string>
  <string>mst_Facility</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HIVDataTablesToMerge {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HIVDataTablesToMerge"]));
            }
            set {
                this["HIVDataTablesToMerge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>zz_admission</string>
  <string>zz_agegroups</string>
  <string>zz_exit</string>
  <string>zz_hivstatus</string>
  <string>zz_hosp</string>
  <string>zz_maritial</string>
  <string>zz_relatives</string>
  <string>zz_sex</string>
  <string>zz_status</string>
  <string>zz_stopcodes</string>
  <string>zz_tbscreen</string>
  <string>zz_toxicity</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CustomTablesToInsert {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomTablesToInsert"]));
            }
            set {
                this["CustomTablesToInsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autoconnect {
            get {
                return ((bool)(this["Autoconnect"]));
            }
            set {
                this["Autoconnect"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.73.195.220/IQWebServices/IQMessaging.asmx")]
        public string IQTools_TzWebReference_IQMessaging {
            get {
                return ((string)(this["IQTools_TzWebReference_IQMessaging"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4944/Service1.asmx")]
        public string IQTools_RemoteWebService_Service1 {
            get {
                return ((string)(this["IQTools_RemoteWebService_Service1"]));
            }
        }
    }
}
